package io.github.danhjalmberg.dronephotoservice.views.components;

import io.github.danhjalmberg.dronephotoservice.settings.AppSettings;

import javax.swing.BorderFactory;
import javax.swing.Box;
import javax.swing.BoxLayout;
import javax.swing.JButton;
import javax.swing.JDialog;
import javax.swing.JFrame;
import javax.swing.JLabel;
import javax.swing.JPanel;
import javax.swing.SwingConstants;
import javax.swing.WindowConstants;
import java.awt.BorderLayout;
import java.awt.Component;
import java.awt.Dimension;
import java.awt.Font;

/**
 * Displays identity, version, authorship, and licensing information
 * about the application.
 * The modal, fixed-size dialog hides on close so the same instance can be shown
 * again.
 *
 * @author Dan Hjälmberg
 */
public class AboutDialog extends JDialog {

    private static final int DIALOG_WIDTH = 460;
    private static final int DIALOG_HEIGHT = 360;

    /**
     * Creates a modal application About dialog.
     *
     * @param owner parent application frame
     */
    public AboutDialog(JFrame owner) {

        super(owner, "About Drone Photo Service", true);

        setDefaultCloseOperation(WindowConstants.HIDE_ON_CLOSE);
        setLayout(new BorderLayout());

        add(createAboutPanel(), BorderLayout.CENTER);
        add(createButtonPanel(), BorderLayout.SOUTH);

        setPreferredSize(new Dimension(DIALOG_WIDTH, DIALOG_HEIGHT));

        pack();
        setLocationRelativeTo(owner);
        setResizable(false);
    }

    /**
     * Creates the application information panel.
     *
     * @return populated About panel
     */
    private JPanel createAboutPanel() {

        JPanel panel = new JPanel();
        panel.setLayout(new BoxLayout(panel, BoxLayout.Y_AXIS));

        panel.setBorder(BorderFactory.createEmptyBorder(28, 32, 16, 32));

        JLabel titleLabel = new JLabel(
                AppSettings.APPLICATION_DISPLAY_NAME,
                SwingConstants.CENTER);

        titleLabel.setFont(titleLabel.getFont().deriveFont(
                Font.BOLD,
                titleLabel.getFont().getSize2D() + 6.0f));

        titleLabel.setAlignmentX(Component.CENTER_ALIGNMENT);

        JLabel descriptionLabel = new JLabel(
                """
                        <html>
                            <div style="text-align: center;">
                                A desktop simulation of autonomous drones processing<br>
                                photo, video, and zoom tasks generated by photo agencies.
                            </div>
                        </html>
                        """,
                SwingConstants.CENTER);

        descriptionLabel.setAlignmentX(Component.CENTER_ALIGNMENT);

        JLabel versionLabel = new JLabel(
                "Version " + AppSettings.APPLICATION_VERSION);

        versionLabel.setAlignmentX(Component.CENTER_ALIGNMENT);

        JLabel authorLabel = new JLabel("Created by Dan Hjälmberg");
        authorLabel.setAlignmentX(Component.CENTER_ALIGNMENT);

        JLabel licenseLabel = new JLabel(
                "Released under the MIT License");

        licenseLabel.setAlignmentX(Component.CENTER_ALIGNMENT);

        JLabel projectLabel = new JLabel(AppSettings.PROJECT_URL);

        projectLabel.setAlignmentX(Component.CENTER_ALIGNMENT);
        projectLabel.setToolTipText(
                "Project source code and documentation");

        panel.add(titleLabel);
        panel.add(Box.createVerticalStrut(18));
        panel.add(descriptionLabel);
        panel.add(Box.createVerticalStrut(18));
        panel.add(versionLabel);
        panel.add(Box.createVerticalStrut(8));
        panel.add(authorLabel);
        panel.add(Box.createVerticalStrut(8));
        panel.add(licenseLabel);
        panel.add(Box.createVerticalStrut(8));
        panel.add(projectLabel);

        return panel;
    }

    /**
     * Creates the bottom button row.
     *
     * @return panel containing the Close button
     */
    private JPanel createButtonPanel() {

        JButton closeButton = new JButton("Close");
        closeButton.addActionListener(event -> setVisible(false));

        JPanel buttonPanel = new JPanel();
        buttonPanel.setBorder(BorderFactory.createEmptyBorder(8, 8, 12, 8));
        buttonPanel.add(closeButton);

        return buttonPanel;
    }
}
