# To use this in your application, make sure that this properties file
# is included in your application JAR (e.g. in package `com.myapp.themes`)
# and invoke `FlatLaf.registerCustomDefaultsSource( "com.myapp.themes" );`
# before setting the look and feel.
# https://www.formdev.com/flatlaf/how-to-customize/#application_properties


# Base app colors
#@background = #2b2b2b
#@foreground = #E6E6E6
#@accentColor = #CC7722


# Standard Swing / FlatLaf UI defaults

#Viewport.background = #427d8e
#Viewport.foreground = #74623b

#Desktop.background = #3E434C
#DesktopIcon.background = #555C68
#DesktopIcon.foreground = #DDDDDD

#RootPane.activeBorderColor = #3D3D3D
#RootPane.background = #2b2b2b
#RootPane.foreground = #DDDDDD
#RootPane.inactiveBorderColor = #ffe70b

Panel.background = #2b2b2b
#Panel.foreground = #b8b82c

#ToolBar.background  = #933364

#Panel.background = #373737
#Label.foreground = #E6E6E6
#TabbedPane.foreground = #E6E6E6
#TabbedPane.selectedBackground = #373737
TabbedPane.font = bold -1

#TabbedPane.cardTabArc = 20
#TabbedPane.tabArc = 20
#Table.background = #2b2b2b
#Table.background = #aa3c3c
Table.gridColor = #2b2b2b
Table.showHorizontalLines = true
Table.showVerticalLines = false
#Table.intercellSpacing = 4
#TableHeader.background = #bf7474
#Table.foreground = #985656

Table.scrollPaneBorder = #4448a5


# FlatLaf-specific styling
#Component.arc = 12
#Button.arc = 12
#TextComponent.arc = 8
#ScrollBar.width = 12

# Your own semantic app colors
#DroneApp.Frame.background = #1E1E1E
#DroneApp.Card.background = #373737
#DroneApp.Text.primary = #E6E6E6